# Generated by Django 3.1.7 on 2021-04-01 08:42

from django.db import migrations

def create_data(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")
    Recipe(name="Avocado Toast", description="Toast with Avocado on it.").save()

    recipe = Recipe.objects.get(name="Avocado Toast")

    Ingredients = apps.get_model("recipes", "Ingredients")
    Ingredients(name="Avocado", qty=1.0, unit="each", recipe=recipe).save()

    Ingredients = apps.get_model("recipes", "Ingredients")
    Ingredients(name="Bread", qty=2.0, unit="slice", recipe=recipe).save()

    Ingredients = apps.get_model("recipes", "Ingredients")
    Ingredients(name="Mozerella", qty=1.0, unit="oz", recipe=recipe).save()

    Procedure = apps.get_model("recipes", "Procedure")
    Procedure(order=1, process="Toast the bread until light brown.", recipe=recipe).save()

    Procedure = apps.get_model("recipes", "Procedure")
    Procedure(order=2, process="Peel and mash the avocado.", recipe=recipe).save()

    Procedure = apps.get_model("recipes", "Procedure")
    Procedure(order=3, process="Slice the cheese.", recipe=recipe).save()

    Procedure = apps.get_model("recipes", "Procedure")
    Procedure(order=4, process="Melt the cheese on the toast.", recipe=recipe).save()

    Procedure = apps.get_model("recipes", "Procedure")
    Procedure(order=5, process="Spread mashed avocado on bread and cheese. Enjoy!", recipe=recipe).save()

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210401_0832'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]

